"""rev1

Revision ID: 17be293f02a3
Revises: b27e15c0db92
Create Date: 2024-09-01 18:53:03.118645

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17be293f02a3"
down_revision = "b27e15c0db92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supply_requests",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("creator_id", sa.BigInteger(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("media_id", sa.String(), nullable=False),
        sa.Column("media_content_type", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.user_id"],
            name=op.f("fk__supply_requests__creator_id__users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__supply_requests")),
    )
    op.create_table(
        "users_supply_requests",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("supply_request_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["supply_request_id"],
            ["supply_requests.id"],
            name=op.f(
                "fk__users_supply_requests__supply_request_id__supply_requests"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk__users_supply_requests__user_id__users"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id",
            "supply_request_id",
            name=op.f("pk__users_supply_requests"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_supply_request")
    op.drop_table("supply_requests")
    # ### end Alembic commands ###
