"""rev2

Revision ID: b34835c83138
Revises: 17be293f02a3
Create Date: 2024-09-22 11:26:35.427380

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b34835c83138"
down_revision = "17be293f02a3"
branch_labels = None
depends_on = None

UserRole = sa.Enum(
    "DEVELOPER",
    "ADMIN",
    "USER",
    "GUEST",
    name="userrole"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    UserRole.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column("role", UserRole, nullable=False, server_default="GUEST"),
    )
    # ### end Alembic commands ###

    def downgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_column("users", "role")
        UserRole.drop(op.get_bind(), checkfirst=True)
        # ### end Alembic commands ###
