"""rev3

Revision ID: 29fb51837d7d
Revises: b34835c83138
Create Date: 2024-09-22 22:30:55.010118

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "29fb51837d7d"
down_revision = "b34835c83138"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    op.add_column("users", sa.Column("fio", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "fio")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
